# Backtest based on historical data

In [1]:
import pandas as pd
import yaml

In [2]:
data = pd.read_csv('hk0005.csv')

In [3]:
data

                   time   open   high  close    low  volume       value
0         2/1/2020 9:31  60.85  60.85  60.75  60.80  196301  11941208.0
1         2/1/2020 9:32  60.80  60.85  60.80  60.85   17200   1046000.0
2         2/1/2020 9:33  60.80  60.85  60.80  60.80    7604    462399.0
3         2/1/2020 9:34  60.85  60.85  60.80  60.80   20816   1265212.0
4         2/1/2020 9:35  60.75  60.80  60.75  60.80   18400   1117880.0
...                 ...    ...    ...    ...    ...     ...         ...
81835  31/12/2020 15:56  40.75  40.75  40.75  40.75       0         0.0
81836  31/12/2020 15:57  40.75  40.75  40.75  40.75       0         0.0
81837  31/12/2020 15:58  40.75  40.75  40.75  40.75       0         0.0
81838  31/12/2020 15:59  40.75  40.75  40.75  40.75       0         0.0
81839  31/12/2020 16:00  40.75  40.75  40.75  40.75       0         0.0

[81840 rows x 7 columns]

In [4]:
data.time

0           2/1/2020 9:31
1           2/1/2020 9:32
2           2/1/2020 9:33
3           2/1/2020 9:34
4           2/1/2020 9:35
               ...
81835    31/12/2020 15:56
81836    31/12/2020 15:57
81837    31/12/2020 15:58
81838    31/12/2020 15:59
81839    31/12/2020 16:00
Name: time, Length: 81840, dtype: object

In [5]:
data['time']=pd.to_datetime(data['time'],format='%d/%m/%Y %H:%M')

In [6]:
data.set_index(data['time'],inplace=True,drop=True)

In [7]:
data=data[['open','high','low','close','volume']]

In [8]:
data.iloc[330]

open          60.65
high          60.95
low           60.90
close         60.65
volume    481612.00
Name: 2020-01-03 09:31:00, dtype: float64

In [9]:
data[330*2:330*3]

                       open    high     low   close   volume
time
2020-01-06 09:31:00  60.300  60.414  60.414  60.100  3261559
2020-01-06 09:32:00  60.409  60.409  60.407  60.407  2000000
2020-01-06 09:33:00  60.407  60.407  60.407  60.407        0
2020-01-06 09:34:00  60.407  60.407  60.407  60.407        0
2020-01-06 09:35:00  60.414  60.414  60.412  60.412  2640000
...                     ...     ...     ...     ...      ...
2020-01-06 15:56:00  60.423  60.423  60.423  60.423        0
2020-01-06 15:57:00  60.423  60.423  60.423  60.423        0
2020-01-06 15:58:00  60.423  60.423  60.423  60.423        0
2020-01-06 15:59:00  60.423  60.423  60.423  60.423        0
2020-01-06 16:00:00  60.000  60.000  60.000  60.000  1315600

[330 rows x 5 columns]

# backtest module

In [10]:
from strat import backtest_all

### parameter

In [11]:
with open("backtest.yaml", "r") as f:
    paradict = yaml.safe_load(f)
    f.close()
paradict=paradict['parameters']

In [12]:
paradict['fee']=0
paradict['profit_coef']=1.008
paradict['stoploss_ratio']=1.008

In [13]:
paradict

{'sar_acce': 0.02,
 'sar_max': 0.2,
 'macd_fast': 12,
 'macd_slow': 26,
 'macd_period': 9,
 'roll_length': 2,
 'vol_ratio': 1.35,
 'profit_coef': 1.008,
 'fee': 0,
 'stoploss_ratio': 1.008,
 'constraint': False,
 'max_duration': 10}

In [14]:
strat=backtest_all.SAR_Strat(paradict,strat="v5", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
value[1].plot()

In [ ]:
strat1=backtest_all.SAR_Strat(paradict,strat="v4", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value1=strat.Backtest()

In [ ]:
value1[1].plot()

In [ ]:
data.close.plot()

In [ ]:
strat=backtest_all.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
value[3].plot()

In [ ]:
value[0].plot()

In [ ]:
strat.plotting('200106')

In [ ]:
from strat import backtest_all

In [ ]:
strat=backtest_all.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
from strat import backtest_sar_test
from strat import backtest_sar

In [ ]:
strat=backtest_sar_test.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
strat=backtest_sar.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
from strat import backtest_macd_test
from strat import backtest_macd

In [ ]:
strat=backtest_macd_test.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
strat=backtest_macd.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
value[0]

In [ ]:
pos[-1]

In [ ]:
pos[pos>5]

In [ ]:
df = pd.DataFrame(value[0],columns=['Only Sar 0.004'])

In [ ]:
df.plot(figsize=(30,20))

In [ ]:
import numpy as np

In [ ]:
for i in np.linspace(0.006,0.008,2):
    paradict['profit_coef']=1+i
    paradict['stoploss_ratio']=1+i
    strat=backtest_sar.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)
    value=strat.Backtest()
    df['Only Sar'+str(i)]=value[0]

In [ ]:
df['close']=data['close']-data['close'][0]

In [ ]:
paradict['profit_coef']=1.004
paradict['stoploss_ratio']=1.004

In [ ]:
from strat import backtest_macd

In [ ]:
df

In [ ]:
strat=backtest_macd.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)

In [ ]:
value=strat.Backtest()

In [ ]:
paradict

In [ ]:
df['only macd 0.004']=value[0]

In [ ]:
for i in np.linspace(0.006,0.008,2):
    paradict['profit_coef']=1+i
    paradict['stoploss_ratio']=1+i
    strat=backtest_macd.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)
    value=strat.Backtest()
    df['Only macd'+str(i)]=value[0]

In [ ]:
from strat import backtest_all

In [ ]:
for i in np.linspace(0.004,0.008,3):
    paradict['profit_coef']=1+i
    paradict['stoploss_ratio']=1+i
    strat=backtest_all.SAR_Strat(paradict,strat="v3", agent="v0", start_time='200102', duration=364, df=data)
    value=strat.Backtest()
    df['Sar macd'+str(i)]=value[0]

In [ ]:
df.plot(figsize=(30,20),fontsize=20).legend(prop={'size': 25})